
package uts.wsd.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightCenterAPI", targetNamespace = "http://soap.wsd.uts/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightCenterAPI {


    /**
     * 
     * @param birthday
     * @param password
     * @param name
     * @param email
     * @return
     *     returns uts.wsd.soap.client.ResponseWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://soap.wsd.uts/", className = "uts.wsd.soap.client.Register")
    @javax.xml.ws.ResponseWrapper(localName = "registerResponse", targetNamespace = "http://soap.wsd.uts/", className = "uts.wsd.soap.client.RegisterResponse")
    @Action(input = "http://soap.wsd.uts/FlightCenterAPI/registerRequest", output = "http://soap.wsd.uts/FlightCenterAPI/registerResponse")
    public uts.wsd.soap.client.ResponseWrapper register(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "birthday", targetNamespace = "")
        String birthday);

    /**
     * 
     * @return
     *     returns uts.wsd.soap.client.ResponseWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://soap.wsd.uts/", className = "uts.wsd.soap.client.Logout")
    @javax.xml.ws.ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://soap.wsd.uts/", className = "uts.wsd.soap.client.LogoutResponse")
    @Action(input = "http://soap.wsd.uts/FlightCenterAPI/logoutRequest", output = "http://soap.wsd.uts/FlightCenterAPI/logoutResponse")
    public uts.wsd.soap.client.ResponseWrapper logout();

    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns uts.wsd.soap.client.ResponseWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://soap.wsd.uts/", className = "uts.wsd.soap.client.Login")
    @javax.xml.ws.ResponseWrapper(localName = "loginResponse", targetNamespace = "http://soap.wsd.uts/", className = "uts.wsd.soap.client.LoginResponse")
    @Action(input = "http://soap.wsd.uts/FlightCenterAPI/loginRequest", output = "http://soap.wsd.uts/FlightCenterAPI/loginResponse")
    public uts.wsd.soap.client.ResponseWrapper login(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
