
package uts.wsd.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightCenterAPI", targetNamespace = "http://soap.wsd.uts", wsdlLocation = "file:/Users/Harrison/Desktop/WSD Assessment 1/src/uts/wsd/soap/FlightCenterAPI.wsdl")
public class FlightCenterAPI_Service
    extends Service
{

    private final static URL FLIGHTCENTERAPI_WSDL_LOCATION;
    private final static WebServiceException FLIGHTCENTERAPI_EXCEPTION;
    private final static QName FLIGHTCENTERAPI_QNAME = new QName("http://soap.wsd.uts", "FlightCenterAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/Harrison/Desktop/WSD Assessment 1/src/uts/wsd/soap/FlightCenterAPI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTCENTERAPI_WSDL_LOCATION = url;
        FLIGHTCENTERAPI_EXCEPTION = e;
    }

    public FlightCenterAPI_Service() {
        super(__getWsdlLocation(), FLIGHTCENTERAPI_QNAME);
    }

    public FlightCenterAPI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTCENTERAPI_QNAME, features);
    }

    public FlightCenterAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTCENTERAPI_QNAME);
    }

    public FlightCenterAPI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTCENTERAPI_QNAME, features);
    }

    public FlightCenterAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightCenterAPI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightCenterAPI
     */
    @WebEndpoint(name = "FlightCenterAPI")
    public FlightCenterAPI getFlightCenterAPI() {
        return super.getPort(new QName("http://soap.wsd.uts", "FlightCenterAPI"), FlightCenterAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightCenterAPI
     */
    @WebEndpoint(name = "FlightCenterAPI")
    public FlightCenterAPI getFlightCenterAPI(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.wsd.uts", "FlightCenterAPI"), FlightCenterAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTCENTERAPI_EXCEPTION!= null) {
            throw FLIGHTCENTERAPI_EXCEPTION;
        }
        return FLIGHTCENTERAPI_WSDL_LOCATION;
    }

}
