
package uts.wsd.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "soap/api", targetNamespace = "http://soap.wsd.uts/", wsdlLocation = "http://localhost:8080/WSD_Assessment_1_war_exploded/soap/api?wsdl")
public class FlightCenterService
    extends Service
{

    private final static URL SOAP_002FAPI_WSDL_LOCATION;
    private final static WebServiceException SOAP_002FAPI_EXCEPTION;
    private final static QName SOAP_002FAPI_QNAME = new QName("http://soap.wsd.uts/", "soap/api");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WSD_Assessment_1_war_exploded/soap/api?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAP_002FAPI_WSDL_LOCATION = url;
        SOAP_002FAPI_EXCEPTION = e;
    }

    public FlightCenterService() {
        super(__getWsdlLocation(), SOAP_002FAPI_QNAME);
    }

    public FlightCenterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAP_002FAPI_QNAME, features);
    }

    public FlightCenterService(URL wsdlLocation) {
        super(wsdlLocation, SOAP_002FAPI_QNAME);
    }

    public FlightCenterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAP_002FAPI_QNAME, features);
    }

    public FlightCenterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightCenterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightCenterAPI
     */
    @WebEndpoint(name = "FlightCenterAPIPort")
    public FlightCenterAPI getFlightCenterAPIPort() {
        return super.getPort(new QName("http://soap.wsd.uts/", "FlightCenterAPIPort"), FlightCenterAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightCenterAPI
     */
    @WebEndpoint(name = "FlightCenterAPIPort")
    public FlightCenterAPI getFlightCenterAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.wsd.uts/", "FlightCenterAPIPort"), FlightCenterAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAP_002FAPI_EXCEPTION!= null) {
            throw SOAP_002FAPI_EXCEPTION;
        }
        return SOAP_002FAPI_WSDL_LOCATION;
    }

}
